services:
  mysql-users:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_USER: admin
      MYSQL_PASSWORD: 123
      MYSQL_DATABASE: users
      MYSQL_ROOT_PASSWORD: 123
    volumes:
      - user_db_data:/var/lib/mysql

volumes:
  user_db_data: